config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :cities
  resources :pages
  resources :messages

  root to: 'welcome#index'

  namespace :manager do
    resources :volunteers do
      collection do
        get "print"
      end
    end
    resources :documents do
      member do
        get "print_document"
      end
    end
    resources :welcome
    resources :messages
  end

  namespace :admin do
    resources :users
    resources :regions
    resources :responsibilities
    resources :congregations
    resources :documents do
      member do
        get "print_document"
      end
    end
    resources :cities
    resources :messages
    resources :vacancies do
      member do
        post 'add_volunteer'
      end
      collection do
        get "managing"
      end
    end
    resources :volunteers do
      collection do
        get "print"
        get "print_managing"
        post 'load_xls'
      end
    end
  end

end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base

  belongs_to :volunteer
  validates_presence_of :name, :starts_at, :ends_at
  validates_uniqueness_of :volunteer_id, if: "volunteer_id.present?"
  scope :by_location, -> (location_number){ where("name ilike ?", "%пост №#{location_number}%" ).order(:number) }
  scope :by_number, -> (number){ where("number = ?", number ).first }
  scope :without_volunteer, -> { where("volunteer_id is null").order(:number) }

  def full_info
    "#{starts_at.strftime("%H:%M")}-#{ends_at.strftime("%H:%M")} #{name}"
  end


end

app/controllers/admin/vacancies_controller.rb
class Admin::VacanciesController < ApplicationController

  before_action :authenticate_user!
  authorize_resource

  before_action :load_model, only: [:edit, :update, :destroy]

  def index
    @vacancies = Vacancy.order(:number)
  end

  def new
    @vacancy = Vacancy.new
  end

  def create
    @vacancy = Vacancy.new vacancy_params
    if @vacancy.save
      redirect_to admin_vacancies_path, notice: "Вакансия добавлена!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @vacancy.update vacancy_params
      redirect_to admin_vacancies_path, notice: "Вакансия обновлена!"
    else
      render :edit
    end
  end

  def destroy
    @vacancy.destroy
    redirect_to admin_vacancies_path notice: "Вакансия удалена!"
  end

  def managing
    @vacancies1 = Vacancy.by_location(1)
  end

  def add_volunteer
    vacancy = Vacancy.find(params[:id])
    if params[:volunteer_id].present?
      volunteer = Volunteer.find(params[:volunteer_id])
      vacancy.volunteer = volunteer
    else
      vacancy.volunteer_id = nil
    end
    vacancy.save
  end

  private

  def load_model
    @vacancy = Vacancy.find params[:id]
  end

  def vacancy_params
    params.require(:vacancy).permit(:name, :comment, :starts_at, :ends_at, :number, :volunteer_id)
  end
  
end

app/helpers/admin/vacancies_helper.rb
module Admin::VacanciesHelper
end

app/views/admin/vacancies/_form.html.haml
= simple_form_for [:admin, @vacancy], :html => { class: "vertical_form"  } do |f|
  = f.input :name, label: "Наименование", autofocus: true, as: :wysihtml5
  = f.input :number, label: "Номер"
  = f.input :starts_at, label: "Начало", as: :time
  = f.input :ends_at, label: "Конец", as: :time
  = f.input :comment, label: "Комментарий", as: :text

  = f.button :submit, "Сохранить", class: 'btn btn-primary'
  = link_to "Отмена", admin_vacancies_path, class: "btn btn-default"

app/views/admin/vacancies/_managing_table.html.haml
- without_vacancy = Volunteer.without_vacancy
- [1,2,3,4,5,6,7,8].each do |number|
  %table.table.table-bordered.table-condensed.table-hover
    %tr
      %th
        = Vacancy.by_location(number).first.try(:name)
  %table.table.table-bordered.table-condensed.table-hover
    - Vacancy.by_location(number).each_with_index do |vacancy, index|
      %tr(style="#{'background-color: #d6fdc2' if vacancy.try(:volunteer).present?}")
        = simple_form_for :volunteer, url: "/admin/volunteers", method: :get, html: { style: "display: inline-block;", class: "form-inline" } do |f|
          %td.td-18
            = index + 1
          %td
            = vacancy_full_info(vacancy).html_safe
          %td
            - volunteer = vacancy.try(:volunteer)
            - volunteers = volunteer.present? ? (without_vacancy << volunteer) : without_vacancy
            = f.input :vacancy_id, label: false, collection: volunteers, label_method: :full_info, value_method: :id, include_blank: "<ВЫБРАТЬ ДОБРОВОЛЬЦА>", selected: vacancy.volunteer_id, input_html: {id: "#{vacancy.id}"}
            - without_vacancy = without_vacancy[0..(without_vacancy.length - 2)] if volunteer.present?

:javascript
  $(":input").change(function() {
    var vac_id = $(this).attr('id')
    var vol_id = $(this).val()
    $.ajax({
      type: "POST",
      url: '/admin/vacancies/' + vac_id + '/add_volunteer?volunteer_id=' + vol_id,
      remote: "true",
    });
  });

app/views/admin/vacancies/add_volunteer.js.erb
noty_success("Выполнено");
$("#managing_table").html("<%= escape_javascript(render :partial => "managing_table") %>");

app/views/admin/vacancies/edit.html.haml
%h1 Редактировать вакансию

= render partial: 'form'

app/views/admin/vacancies/index.html.haml
.top-right-actions
  = link_to "Добавить", new_admin_vacancy_path, class: "btn btn-primary"
%h1 Вакансии на служение (#{@vacancies.count})

%table.table.table-bordered.table-condensed.table-hover
  %tr
    %th.td-18
      \#
    %th.td-18
    %th
      Название
    %th
      Время
    %th
      Комментарии
    %th.td-18

  - @vacancies.each_with_index do |vacancy, index|

    %tr
      %td.td-18
        = index + 1
      %td.td-18
        = admin_edit_link(vacancy)
      %td
        #{vacancy.number}) #{vacancy.name.html_safe}
      %td
        #{vacancy.starts_at.strftime("%H:%M")}-#{vacancy.ends_at.strftime("%H:%M")}
      %td
        = vacancy.comment
      %td.td-18
        = delete_trash_link admin_vacancy_path(vacancy)

app/views/admin/vacancies/managing.html.haml
#managing_table
  = render :partial => "managing_table"

:javascript
  $(":input").change(function() {
    var vac_id = $(this).attr('id')
    var vol_id = $(this).val()
    $.ajax({
      type: "POST",
      url: '/admin/vacancies/' + vac_id + '/add_volunteer?volunteer_id=' + vol_id,
      remote: "true",
    });
  });

app/views/admin/vacancies/new.html.haml
%h1 Добавить вакансию

= render partial: 'form'