config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :cities
  resources :pages
  resources :messages

  root to: 'welcome#index'

  namespace :manager do
    resources :volunteers do
      collection do
        get "print"
      end
    end
    resources :documents do
      member do
        get "print_document"
      end
    end
    resources :welcome
    resources :messages
  end

  namespace :admin do
    resources :users
    resources :regions
    resources :responsibilities
    resources :congregations
    resources :documents do
      member do
        get "print_document"
      end
    end
    resources :cities
    resources :messages
    resources :vacancies do
      member do
        post 'add_volunteer'
      end
      collection do
        get "managing"
      end
    end
    resources :volunteers do
      collection do
        get "print"
        get "print_managing"
        post 'load_xls'
      end
    end
  end

end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base

  belongs_to :congregation
  belongs_to :responsibility
  has_one :vacancy
  scope :by_congregation_id, -> congregation_id { where("congregation_id = ?", congregation_id) }
  scope :without_vacancies, -> { where("id not in (?)", Vacancy.where("volunteer_id is not null").pluck(:volunteer_id))}

  validates :age, numericality: { greater_than: 18}
  validates_presence_of :congregation_id, :last_name, :first_name, :age,
                        :convenient_start_time, :convenient_end_time, :will_be_since_8, :car,
                        :will_be_until_17, :outdoor, :phone, :responsibility_id

  def full_info
    "#{congregation.city.region.name[0]}.обл. #{congregation.name} #{last_name.strip} #{first_name} #{age}л. / (#{responsibility.name}) /  время #{convenient_time} #{"/ Улица" if outdoor == 1} / #{comment}"
  end

  def full_info_for_print
    "#{congregation.city.region.name[0]}.#{congregation.name} (#{responsibility.name}) #{last_name.strip} #{first_name} #{age}"
  end

  def convenient_time
    "#{convenient_start_time.strftime("%H:%M")}-#{convenient_end_time.strftime("%H:%M")}"
  end

  def city_and_congregation
    congregation.city.name == congregation.name ? "#{congregation.name}" : "#{congregation.city.name} #{congregation.name}"
  end

  def self.without_vacancy
    if Vacancy.where("volunteer_id is not null").pluck(:volunteer_id).count > 0
      self.where("id not in (?)", Vacancy.where("volunteer_id is not null").pluck(:volunteer_id)).order(:congregation_id)
    else
      self.order(:congregation_id)
    end
  end

end

app/controllers/admin/volunteers_controller.rb
class Admin::VolunteersController < ApplicationController

  before_filter :authenticate_user!
  authorize_resource

  before_filter :load_model, only: [:edit, :show, :update, :destroy]

  def index
    scope = Volunteer.joins(:congregation)
    @part, @order, @congregation_id, @vacancy = nil, nil, nil, nil
    if params[:volunteer]
      @part = params[:volunteer][:part]
      @order = params[:volunteer][:order]
      @congregation_id = params[:volunteer][:congregation_id]
      @vacancy = params[:volunteer][:vacancy]
      scope = scope.where("email ilike :part or first_name ilike :part or last_name ilike :part or phone ilike :part", part: "%#{@part}%") if @part.present?
      scope = scope.where("congregation_id = ?", @congregation_id) if @congregation_id.present?
      scope = scope.where("vacancy_id is null") if @vacancy == "2"
      scope = scope.where("vacancy_id is not null") if @vacancy == "1"
      scope = scope.order("#{@order}") if @order.present?
    end
    @volunteers = scope
  end

  def show
  end

  def new
    @volunteer = Volunteer.new
  end

  def create
    @volunteer = Volunteer.new params_volunteer
    if @volunteer.save
      redirect_to admin_volunteers_path, notice: "Доброволец успешно создан!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @volunteer.update params_volunteer
      redirect_to admin_volunteers_path, notice: "Информация о добровольце обновлена"
    else
      render :edit
    end
  end

  def destroy
    @volunteer.destroy
    redirect_to admin_volunteers_path
  end

  def print
    @volunteers = Volunteer.order(:congregation_id).order(:responsibility_id)
    render layout: false
  end

  def print_managing
    @vacancies = Vacancy.order(:number)
    render layout: false
  end

  def load_xls
    @congregation = Congregation.find params[:congregation_id]
    Uploads::Manager.async_process_file params[:file], @congregation
    # full_file_path = Uploads::Manager.save_file(params[:file])
    # @upload = Upload.create!(:supplier_id => @client.id, storage_life_days: @client.store.storage_life_days)
    # Uploads::Manager.process_file(full_file_path, @client, @upload)
    redirect_to admin_volunteers_path, notice: "Файл принят в обработку!"
  end

  private

  def params_volunteer
    params.require(:volunteer).permit(:congregation_id, :last_name, :first_name, :age, :service_time_id,
                                      :convenient_start_time, :convenient_end_time, :will_be_since_8, :car,
                                      :will_be_until_17, :outdoor,  :service_id, :phone,:email, :comment, :responsibility_id)
  end

  def load_model
    @volunteer = Volunteer.find params[:id]
  end


end

app/controllers/manager/volunteers_controller.rb
class Manager::VolunteersController < ApplicationController

  before_filter :authenticate_user!
  authorize_resource

  before_filter :load_model, only: [:edit, :show, :update, :destroy]

  def index
    @congregation = current_user.congregation
    @volunteers = Volunteer.by_congregation_id(@congregation.id)
  end

  def show
  end

  def new
    @volunteer = Volunteer.new
  end

  def create
    @volunteer = current_user.congregation.volunteers.build params_volunteer
    if @volunteer.save
      redirect_to manager_volunteers_path, notice: "Доброволец успешно создан!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @volunteer.update params_volunteer
      redirect_to manager_volunteers_path, notice: "Информация о добровольце обновлена"
    else
      render :edit
    end
  end

  def destroy
    if @volunteer.vacancy.present?
      redirect_to manager_volunteers_path, alert: "Нельзя удалить уже назначенного добровольца! Напишите Администратору!" if @volunteer.vacancy.present?
    else
      @volunteer.destroy
      redirect_to manager_volunteers_path, notice: "Доброволец успешно удален!"
    end
  end

  def print
    @congregation = current_user.congregation
    @volunteers = Volunteer.by_congregation_id(@congregation.id)
    render layout: false
  end

  private

  def params_volunteer
    params.require(:volunteer).permit( :last_name, :first_name, :age, :service_time_id,
                                      :convenient_start_time, :convenient_end_time, :will_be_since_8, :car,
                                      :will_be_until_17, :outdoor, :phone,:email, :comment, :responsibility_id)
  end

  def load_model
    @volunteer = Volunteer.find params[:id]
  end

end

app/helpers/admin/volunteers_helper.rb
module Admin::VolunteersHelper
end

app/helpers/manager/volunteers_helper.rb
module Manager::VolunteersHelper
end

app/views/admin/volunteers/_form.html.haml
= simple_form_for [:admin, @volunteer], :html => { :id => "volunteer_form", :class => 'vertical-form', :role => "form", autocomplete: "off" } do |f|
  = f.input :congregation_id, label: "Собрание", collection: Congregation.order(:name), label_method: :full_info, value_mathod: :id, include_blank: false
  = f.input :last_name, label: "Фамилия"
  = f.input :first_name, label: "Имя"
  = f.input :age, label: "Возраст"
  = f.input :responsibility_id, label: "Назначение", collection: Responsibility.order(:name), label_method: :name, value_mathod: :id, include_blank: false
  = f.input :convenient_start_time, label: "Время начала служения", as: :time
  = f.input :convenient_end_time, label: "Время окончания служения", as: :time
  = f.input :will_be_since_8, label: "Приедет в 8:00", as: :boolean
  = f.input :will_be_until_17, label: "Останется до 17:00", as: :boolean
  = f.input :outdoor, label: "Может на улице", as: :boolean
  = f.input :car, label: "Автомобилист", as: :boolean
  = f.input :phone, label: "Телефон"
  -#= f.input :email, label: "EMAIL"
  = f.input :comment, label: "Комментарии"

  = f.submit "Сохранить", class: "btn btn-primary"
  = link_to "Отмена", admin_volunteers_path, class: "btn btn-default"

:javascript

  $(document).ready(function(){

    $("#volunteer_phone").mask("(999) 999-9999");

  });

app/views/admin/volunteers/edit.html.haml
%h1 Редактирование добровольца

= render partial: "form"

app/views/admin/volunteers/index.html.haml
.top-right-actions
  = simple_form_for :volunteer, url: "/admin/volunteers", method: :get, html: { style: "display: inline-block;", class: "form-inline" } do |f|
    = f.input :vacancy, label: false, collection: {"ВСЕ": nil, "С НАЗНАЧЕНИЕМ": 1, "БЕЗ НАЗНАЧЕНИЯ": 2}, include_blank: false, selected: @vacancy
    = f.input :order, label: false, collection: [["ПО ФАМИЛИИ", "last_name"], ["ПО СОБРАНИЮ", "congregations.name"]], include_blank: false, selected: @order
    = f.input :congregation_id, label: false, collection: Congregation.order(:name), label_method: :full_info, value_method: :id, include_blank: "<ВЫБРАТЬ СОБРАНИЕ>", selected: @congregation_id
    = f.input :part, label: false, input_html: { value: "#{@part}" }
    = f.submit "Найти", class: "btn btn-default"


%h1 Добровольцы (#{@volunteers.count})

%table.table.table-bordered
  %tr
    %th.td-18
      \#
    %th.td-18
    %th
      Сведения
    %th
      Время
    %th
      08
    %th
      17
    %th
      УЛ
    %th
      Авт
    %th
      Телефон
    -#%th
    -#  EMAIL
    -#%th
    -#  Комментарии
    %th
      Время и место служения
    %th.td-18
  - @volunteers.each_with_index do |volunteer, index|
    %tr
      %td
        = index + 1
      %td
        = edit_link [:edit,:admin , volunteer]
      %td
        = volunteer.full_info
      %td.td-nowrap
        = convenient_time(volunteer)
      %td.td-center.pointer(title="Будет к 8:00")
        = yes_or_no_icon(volunteer.will_be_since_8)
      %td.td-center.pointer(title="Будет до 17:00")
        = yes_or_no_icon(volunteer.will_be_until_17)
      %td.td-center.pointer(title="Может на улице")
        = yes_or_no_icon(volunteer.outdoor)
      %td.td-center.pointer(title="Автомобилист")
        = yes_or_no_icon(volunteer.car)
      %td.td-nowrap
        = volunteer.phone
      -#%td
      -#  = volunteer.email
      -#%td
      -#  = volunteer.comment
      %td
        = volunteer.vacancy.try(:full_info).try(:html_safe)
      %td
        = delete_link [:admin, volunteer]

= link_to "Добавить", new_admin_volunteer_path, class: "btn btn-primary"
= link_to "Печать", print_admin_volunteers_path, target: "_blank", class: "btn btn-default"
= link_to "Печать схемы", print_managing_admin_volunteers_path, target: "_blank", class: "btn btn-default"

= form_tag load_xls_admin_volunteers_path, :multipart => true, :id => "upload_form", :style => "margin: 20px 0 10px 0" do
  %div(style="background-color: lightgray; border-radius: 5px; padding: 15px;     height: 70px;")
    = select_tag :congregation_id, options_from_collection_for_select(Congregation.all, :id, :full_info)
    %span#file_name
      Файл не выбран
    %span(style="float: right;")
      %div(style="margin-top: -7px;")
        %span.btn.btn-success.fileinput-button.pointer(style="margin-right: 10px;")
          %i.fa.fa-plus
          %span Выбрать...
          = file_field_tag :file, id: "file"
        %span.fileinput-button.pointer
          = submit_tag "Отправить", class: 'btn btn-primary'

:javascript

  $(document).ready(function(){

    $("#file").change(function (e) {
      var file_name = this.files[0].name;
      $("#file_name").html(file_name);

    });

  });

app/views/admin/volunteers/new.html.haml
%h1 Новый доброволец

= render partial: "form"

app/views/admin/volunteers/print.html.haml
= javascript_include_tag 'application', 'data-turbolinks-track' => true
= stylesheet_link_tag    'admin', media: 'all'
.portrait
  -#%h1 Добровольцы (#{@volunteers.count})

  %table.table.table-bordered(style="font-size: 11px")
    %tr
      %th.td-18
      %th
        Сведения
      %th
        Время
      %th
        Телефон
      %th
        Время и место служения

    - @volunteers.each_with_index do |volunteer, index|
      %tr
        %td.td-center
          = index + 1
        %td
          = volunteer.full_info_for_print
        %td.td-nowrap
          = volunteer.convenient_time
        %td.td-nowrap
          = volunteer.phone
        %td
          = volunteer.vacancy.try(:full_info).try(:html_safe)

  = raw immediate_print

app/views/admin/volunteers/print_managing.html.haml
= javascript_include_tag 'application', 'data-turbolinks-track' => true
= stylesheet_link_tag    'admin', media: 'all'
.portrait
  -#%h1 Схема вакансий (#{@vacancies.count})


  %table.table.table-bordered(style="font-size: 11px")
    %tr
      %th.td-18
      %th
        Вакансия
      %th
        Доброволец
      %th
        Телефон

    - @vacancies.each_with_index do |vacancy, index|
      %tr
        %td.td-center
          = index + 1
        %td
          = vacancy_full_info(vacancy).html_safe
        %td
          = vacancy.volunteer.try(:full_info_for_print)
        %td
          = vacancy.volunteer.try(:phone)

  = raw immediate_print