config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :cities
  resources :pages
  resources :messages

  root to: 'welcome#index'

  namespace :manager do
    resources :volunteers do
      collection do
        get "print"
      end
    end
    resources :documents do
      member do
        get "print_document"
      end
    end
    resources :welcome
    resources :messages
  end

  namespace :admin do
    resources :users
    resources :regions
    resources :responsibilities
    resources :congregations
    resources :documents do
      member do
        get "print_document"
      end
    end
    resources :cities
    resources :messages
    resources :vacancies do
      member do
        post 'add_volunteer'
      end
      collection do
        get "managing"
      end
    end
    resources :volunteers do
      collection do
        get "print"
        get "print_managing"
        post 'load_xls'
      end
    end
  end

end

app/models/congregation.rb
class Congregation < ActiveRecord::Base

  belongs_to :city
  has_many :volunteers
  validates_presence_of :name, :number, :city_id

  def full_info
    "#{city.name} #{name} (#{number})"
  end

end

app/controllers/admin/congregations_controller.rb
class Admin::CongregationsController < ApplicationController

  before_action :authenticate_user!
  authorize_resource

  before_action :load_model, only: [:edit, :update, :destroy]

  def index
    @congregations = Congregation.order(:name)
  end

  def new
    @congregation = Congregation.new
  end

  def create
    @congregation = Congregation.new congregation_params
    if @congregation.save
      redirect_to admin_congregations_path, notice: "Собрание успешно создано!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @congregation.update congregation_params
      redirect_to admin_congregations_path, notice: "Собрание успешно обновлено!"
    else
      render :edit
    end
  end

  def destroy
    @congregation.destroy
    redirect_to admin_congregations_pathб notice: "Собрание успешно удалено!"
  end

  private

  def load_model
    @congregation = Congregation.find params[:id]
  end

  def congregation_params
    params.require(:congregation).permit(:name, :number, :city_id)
  end


end

app/helpers/admin/congregations_helper.rb
module Admin::CongregationsHelper
end

app/views/admin/congregations/_form.html.haml
= simple_form_for [:admin, @congregation], :html => { class: "vertical_form"  } do |f|
  = f.input :name, label: "Наименование", autofocus: true
  = f.input :city_id, label: "Город", collection: City.order(:name), label_method: :name, value_method: :id, include_blank: false
  = f.input :number, label: "Номер"

  = f.button :submit, "Сохранить", class: 'btn btn-primary'
  = link_to "Отмена", admin_congregations_path, class: "btn btn-default"

app/views/admin/congregations/edit.html.haml
%h1 Редактировать собрание

= render partial: 'form'

app/views/admin/congregations/index.html.haml
.top-right-actions
  = link_to "Добавить", new_admin_congregation_path, class: "btn btn-primary"
%h1 Собрания (#{@congregations.count})

%table.table.table-bordered.table-condensed.table-hover
  %tr
    %th.td-18
      \#
    %th.td-18
    %th
      Город
    %th
      Наименование
    %th
      Номер
    %th.td-18.td-nowrap
      Д-цы
    %th.td-18

  - @congregations.each_with_index do |congregation, index|

    %tr(style="#{'background-color: pink' if congregation.volunteers.empty?}")
      %td.td-18
        = index + 1
      %td.td-18
        = admin_edit_link(congregation)
      %td
        = congregation.city.name
      %td
        = congregation.name
      %td
        = congregation.number
      %td.pointer.td-center(title="Кол-во добровольцев")
        = congregation.volunteers.count
      %td.td-18
        = delete_trash_link admin_congregation_path(congregation)

app/views/admin/congregations/new.html.haml
%h1 Добавить собрание

= render partial: 'form'